In [3]:
import pandas as pd
import os

print(os.listdir("phase3_clean_data"))

['ratings_clean.csv', 'reviews_clean.csv', 'subscribers_clean.csv', 'titles_clean.csv', 'watchlist_clean.csv', 'watch_history_clean.csv']

In [4]:
#loading clean dataset


#path to phase3 cleaned dataset

phase3_data_path = "phase3_clean_data"

#loading clean datasets


subscribers = pd.read_csv(os.path.join(phase3_data_path,"subscribers_clean.csv"))

watch_history = pd.read_csv(os.path.join(phase3_data_path,"watch_history_clean.csv"))

titles = pd.read_csv(os.path.join(phase3_data_path,"titles_clean.csv"))

ratings = pd.read_csv(os.path.join(phase3_data_path,"ratings_clean.csv"))

reviews = pd.read_csv(os.path.join(phase3_data_path,"reviews_clean.csv"))

watchlist = pd.read_csv(os.path.join(phase3_data_path,"watchlist_clean.csv"))

print("All Cleaned Datasets Loaded Sucessfully.")

All Cleaned Datasets Loaded Sucessfully.

In [9]:
#verifying the data

print("subscribers:", subscribers.shape)
print("watch_history:",watch_history.shape)
print("titles:",titles.shape)
print("ratings:",ratings.shape)
print("reviews:",reviews.shape)
print("watchlist:",watchlist.shape)

subscribers: (15000, 14)
watch_history: (650000, 11)
titles: (9000, 21)
ratings: (130000, 5)
reviews: (110000, 7)
watchlist: (65000, 5)

In [10]:
# creating first KPI'S
#Total Watch Hours 
#For calculatinf formula is sum(watch_duration_min)/60


print(watch_history[["watch_duration_min"]].info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650000 entries, 0 to 649999
Data columns (total 1 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   watch_duration_min  650000 non-null  float64
dtypes: float64(1)
memory usage: 5.0 MB
None

In [11]:
#Calculating Total Watch Hours

total_watch_hours = watch_history['watch_duration_min'].sum() / 60

print(f"Total Watch Hours: {total_watch_hours:,.2f}")

Total Watch Hours: 3,333,467.73

In [12]:
#calculating 2nd KPI'S for that we'll use Total Subscribersx100
#Active Rate

print(subscribers.columns.tolist())

['subscriber_id', 'signup_date', 'country', 'region', 'age', 'gender', 'plan_type', 'monthly_price_usd', 'household_size', 'primary_device', 'payment_method', 'tenure_months', 'is_active', 'churn_date']

In [14]:
#we have field is_active ,directly we can calculate Active Rate from the subscribers table

#validating


print(subscribers['is_active'].value_counts(dropna=False))

is_active
True     11199
False     3801
Name: count, dtype: int64

In [15]:
# calculating Active Rate

total_subscribers = subscribers['subscriber_id'].nunique()
active_subscribers = subscribers['is_active'].sum()

active_rate = (active_subscribers / total_subscribers) * 100

print(f"Total Subscribers: {total_subscribers:,}")
print(f"Active Subscribers: {active_subscribers:,}")
print(f"Active Rate: {active_rate:.2f}%")

Total Subscribers: 15,000
Active Subscribers: 11,199
Active Rate: 74.66%

In [16]:
#calculating KPI 3 — Churn Rate for that formula will be used (Inactive subscriber/Total subscriber)x100


inactive_subscribers = (~subscribers['is_active']).sum()

churn_rate = (inactive_subscribers / total_subscribers) * 100

print(f"Inactive Subscribers: {inactive_subscribers:,}")
print(f"Churn Rate: {churn_rate:.2f}%")

Inactive Subscribers: 3,801
Churn Rate: 25.34%

In [18]:
#Calculating KPI 4 — Avg Completion Rate for that we need

#AVG(completion__pct)

#validating the columns


print(watch_history['completion_pct'].describe())
print(watch_history['completion_pct'].isna().sum())

count    650000.000000
mean         65.310710
std          22.606162
min           1.000000
25%          49.200000
50%          68.300000
75%          84.100000
max         100.000000
Name: completion_pct, dtype: float64
0

In [19]:
#calculating Avg Completion rate

avg_completion_rate = watch_history['completion_pct'].mean()

print(f"Avg Completion Rate: {avg_completion_rate:.2f}%")

Avg Completion Rate: 65.31%

In [20]:
#calculating the KPI 5 — Monthly Recurring Revenue (MRR).

#validating the required columns

print(subscribers[['monthly_price_usd', 'is_active']].info())
print("\nMissing values:")
print(subscribers[['monthly_price_usd', 'is_active']].isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   monthly_price_usd  15000 non-null  float64
 1   is_active          15000 non-null  bool
dtypes: bool(1), float64(1)
memory usage: 132.0 KB
None

Missing values:
monthly_price_usd    0
is_active            0
dtype: int64

In [21]:
#calculating Monthly Recurring Revenue (MRR)

mrr = subscribers.loc[
    subscribers['is_active'],
    'monthly_price_usd'
].sum()

print(f"Monthly Recurring Revenue (MRR): ${mrr:,.2f}")

Monthly Recurring Revenue (MRR): $175,868.51

In [22]:
#CALCULATING KPI 6 — ARPU (Average Revenue Per User).for that formulat
# ARPU = MRR / Active Subscribrs


arpu = mrr / active_subscribers

print(f"ARPU: ${arpu:.2f} per active subscriber")

ARPU: $15.70 per active subscriber

In [23]:
#calculating KPI 7 — Average Watch Time per Subscriber.for that formula 
#Avg Watch Time  = Total Watch Hours / Active Subscribers

avg_watch_time_per_subscriber = total_watch_hours / active_subscribers

print(f"Avg Watch Time per Active Subscriber: {avg_watch_time_per_subscriber:.2f} hours")

Avg Watch Time per Active Subscriber: 297.66 hours

In [ ]:
#calculating KPI 8 — Watchlist Conversion

#for this we should identify
#watchlist entries
#watched entries

In [24]:
#checking Watchlist Colums

print(watchlist.columns.tolist())
print("\nData types:")
print(watchlist.dtypes)

['watchlist_id', 'subscriber_id', 'title_id', 'added_date', 'watched']

Data types:
watchlist_id      int64
subscriber_id    object
title_id         object
added_date       object
watched            bool
dtype: object

In [25]:
print(watchlist['watched'].value_counts())

watched
False    34952
True     30048
Name: count, dtype: int64

In [27]:
#calculating watchlist conversion

total_watchlist_entries = len(watchlist)
watched_entries = watchlist['watched'].sum()

watchlist_conversion = (
    watched_entries / total_watchlist_entries) * 100

print(f"Watchlist Conversion: {watchlist_conversion:.2f}%")

Watchlist Conversion: 46.23%

In [28]:
#calculating the KPI 9 — Hit Concentration.

#inspecting columns

print("Watch History columns:")
print(watch_history.columns.tolist())

print("\nTitles columns:")
print(titles.columns.tolist())

Watch History columns:
['watch_id', 'subscriber_id', 'title_id', 'watch_date', 'device', 'region', 'content_duration_min', 'watch_duration_min', 'completion_pct', 'completed', 'duration_outlier_flag']

Titles columns:
['title_id', 'title_name', 'type', 'primary_genre', 'country', 'language', 'release_year', 'date_added', 'maturity_rating', 'seasons', 'content_duration_min', 'is_original', 'license_type', 'director', 'cast', 'quality_score', 'popularity_score', 'license_cost_usd', 'license_expiry', 'total_watch_hours', 'total_plays']

In [30]:
# for Hit Concentration ,formula we need
#  (Plays from top 10% titles / Total plays) x 100

#checking  the play distribution

plays_per_title = watch_history['title_id'].value_counts()

total_unique_titles = plays_per_title.size

print(f"Total unique titles watched: {total_unique_titles}")
print(f"Total plays: {plays_per_title.sum():,}")
print(f"Top title plays: {plays_per_title.max():,}")

Total unique titles watched: 9000
Total plays: 650,000
Top title plays: 4,436

In [31]:
# Top 10 titles

top_10_percent_count = int(total_unique_titles * 0.10)

top_10_titles = plays_per_title.head(top_10_percent_count)

top_10_plays = top_10_titles.sum()
total_plays = plays_per_title.sum()

print(f"Top 10% titles: {top_10_percent_count}")
print(f"Plays from top 10% titles: {top_10_plays:,}")
print(f"Total plays: {total_plays:,}")

Top 10% titles: 900
Plays from top 10% titles: 201,417
Total plays: 650,000

In [32]:
#Calculating Hit Conversion

hit_concentration = (
    top_10_plays / total_plays
) * 100

print(f"Hit Concentration: {hit_concentration:.2f}%")

Hit Concentration: 30.99%

In [33]:
# Calculating KPI 10 — Originals Share of Hours.

# validating Is_original

print(titles['is_original'].value_counts())
print("\nMissing values:")
print(titles['is_original'].isna().sum())

is_original
False    7034
True     1966
Name: count, dtype: int64

Missing values:
0

In [34]:
#we need to connect watch_history to titles using title_id

title_original_lookup = titles[['title_id', 'is_original']]

print(title_original_lookup.head())
print(f"\nRows in title lookup: {len(title_original_lookup):,}")

    title_id  is_original
0  TTL200000         True
1  TTL200001        False
2  TTL200002        False
3  TTL200003        False
4  TTL200004        False

Rows in title lookup: 9,000

In [36]:
#validating title_id

print(f"Total title rows: {len(title_original_lookup):,}")
print(f"Unique title IDs: {title_original_lookup['title_id'].nunique():,}")

print("Duplicate title IDs:",
    title_original_lookup['title_id'].duplicated().sum())

Total title rows: 9,000
Unique title IDs: 9,000
Duplicate title IDs: 0

In [37]:
#Joining the data

watch_with_original = watch_history.merge(
    title_original_lookup,
    on='title_id',
    how='left'
)

print(f"Watch history rows before join: {len(watch_history):,}")
print(f"Rows after join: {len(watch_with_original):,}")

print("\nMissing is_original after join:")
print(watch_with_original['is_original'].isna().sum())

Watch history rows before join: 650,000
Rows after join: 650,000

Missing is_original after join:
0

In [38]:
#alculating Original Content Watch Hours

original_watch_hours = (watch_with_original.loc[
        watch_with_original['is_original'],
        'watch_duration_min'].sum() / 60)

print(f"Original Content Watch Hours: {original_watch_hours:,.2f}")

Original Content Watch Hours: 905,661.77

In [39]:
#Original Shares

#Originals Share = Original Watch Hours ÷ Total Watch Hours × 100

originals_share_hours = (
    original_watch_hours / total_watch_hours) * 100

print(f"Originals Share of Hours: {originals_share_hours:.2f}%")

Originals Share of Hours: 27.17%

## creating KPI Table

In [42]:
kpi_results = pd.DataFrame({
    'KPI': [
        'Total Watch Hours',
        'Active Rate',
        'Churn Rate',
        'Avg Completion Rate',
        'Monthly Recurring Revenue (MRR)',
        'ARPU',
        'Avg Watch Time per Active Subscriber',
        'Watchlist Conversion',
        'Hit Concentration',
        'Originals Share of Hours'],
    
    'Value': [
        total_watch_hours,
        active_rate,
        churn_rate,
        avg_completion_rate,
        mrr,
        arpu,
        avg_watch_time_per_subscriber,
        watchlist_conversion,
        hit_concentration,
        originals_share_hours]})

kpi_results

                                    KPI         Value
0                     Total Watch Hours  3.333468e+06
1                           Active Rate  7.466000e+01
2                            Churn Rate  2.534000e+01
3                   Avg Completion Rate  6.531071e+01
4       Monthly Recurring Revenue (MRR)  1.758685e+05
5                                  ARPU  1.570395e+01
6  Avg Watch Time per Active Subscriber  2.976576e+02
7                  Watchlist Conversion  4.622769e+01
8                     Hit Concentration  3.098723e+01
9              Originals Share of Hours  2.716876e+01

In [41]:
#formating table

kpi_results_formatted = kpi_results.copy()

kpi_results_formatted['Value'] = [
    f"{total_watch_hours:,.2f} hours",
    f"{active_rate:.2f}%",
    f"{churn_rate:.2f}%",
    f"{avg_completion_rate:.2f}%",
    f"${mrr:,.2f}",
    f"${arpu:.2f}",
    f"{avg_watch_time_per_subscriber:.2f} hours",
    f"{watchlist_conversion:.2f}%",
    f"{hit_concentration:.2f}%",
    f"{originals_share_hours:.2f}%"
]

kpi_results_formatted

                                    KPI               Value
0                     Total Watch Hours  3,333,467.73 hours
1                           Active Rate              74.66%
2                            Churn Rate              25.34%
3                   Avg Completion Rate              65.31%
4       Monthly Recurring Revenue (MRR)         $175,868.51
5                                  ARPU              $15.70
6  Avg Watch Time per Active Subscriber        297.66 hours
7                  Watchlist Conversion              46.23%
8                     Hit Concentration              30.99%
9              Originals Share of Hours              27.17%

In [43]:
kpi_results_formatted.style.hide(axis="index")

In [64]:
kpi_results_formatted.to_csv("kpi_results_formatted.csv", index=False)

In [44]:
#calculating Cohort Retention.

#validating subscriber dates

print(subscribers[['signup_date', 'is_active']].info())

print("\nMissing values:")
print(subscribers[['signup_date', 'is_active']].isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   signup_date  15000 non-null  object
 1   is_active    15000 non-null  bool
dtypes: bool(1), object(1)
memory usage: 132.0+ KB
None

Missing values:
signup_date    0
is_active      0
dtype: int64

In [47]:
#validating churn_date and the date range


print(subscribers[['signup_date', 'churn_date']].head())

print("\nChurn date data type:")
print(subscribers['churn_date'].dtype)

print("\nMissing churn dates:")
print(subscribers['churn_date'].isna().sum())

print("\nSignup date range:")
print(subscribers['signup_date'].min(), "to", subscribers['signup_date'].max())

print("\nChurn date range:")
print(subscribers['churn_date'].min(), "to", subscribers['churn_date'].max())

  signup_date churn_date
0  2023-01-09        NaT
1  2020-02-05 2022-12-08
2  2022-04-15        NaT
3  2024-10-10        NaT
4  2020-04-12 2021-12-15

Churn date data type:
datetime64[ns]

Missing churn dates:
11199

Signup date range:
2016-01-13 00:00:00 to 2026-05-31 00:00:00

Churn date range:
2016-04-03 00:00:00 to 2026-06-30 00:00:00

In [46]:
subscribers['signup_date'] = pd.to_datetime(subscribers['signup_date'])
subscribers['churn_date'] = pd.to_datetime(subscribers['churn_date'])

print(subscribers[['signup_date', 'churn_date']].dtypes)

signup_date    datetime64[ns]
churn_date     datetime64[ns]
dtype: object

In [48]:
#Creating the signup cohort month


subscribers['cohort_month'] = subscribers['signup_date'].dt.to_period('M')

print(subscribers[['signup_date', 'cohort_month']].head())

  signup_date cohort_month
0  2023-01-09      2023-01
1  2020-02-05      2020-02
2  2022-04-15      2022-04
3  2024-10-10      2024-10
4  2020-04-12      2020-04

In [49]:
#Creating 3-month checkpoint

subscribers['3_month_date'] = (subscribers['signup_date'] + pd.DateOffset(months=3))

print(subscribers[['signup_date', '3_month_date', 'churn_date']].head())

  signup_date 3_month_date churn_date
0  2023-01-09   2023-04-09        NaT
1  2020-02-05   2020-05-05 2022-12-08
2  2022-04-15   2022-07-15        NaT
3  2024-10-10   2025-01-10        NaT
4  2020-04-12   2020-07-12 2021-12-15

In [50]:
#data cutoff date


data_end_date = max(subscribers['signup_date'].max(),subscribers['churn_date'].max())

print(f"Data End Date: {data_end_date.date()}")

Data End Date: 2026-06-30

In [51]:
#3-month retained flag

subscribers['retained_3_months'] = (
    (subscribers['3_month_date'] <= data_end_date) &
    (subscribers['churn_date'].isna() |
        (subscribers['churn_date'] > subscribers['3_month_date'])))

print(subscribers['retained_3_months'].value_counts())

retained_3_months
True     14187
False      813
Name: count, dtype: int64

In [52]:
#Separate eligible subscribers

eligible_3_months = subscribers['3_month_date'] <= data_end_date

subscribers['retained_3_months'] = (eligible_3_months &
    (subscribers['churn_date'].isna() |
        (subscribers['churn_date'] > subscribers['3_month_date'])))

print("Eligible for 3-month retention:", eligible_3_months.sum())
print("Retained at 3 months:", subscribers['retained_3_months'].sum())

Eligible for 3-month retention: 14567
Retained at 3 months: 14187

In [53]:
#3-month retention rate

retention_3_months = (
    subscribers['retained_3_months'].sum() /
    eligible_3_months.sum()) * 100

print(f"3-Month Retention Rate: {retention_3_months:.2f}%")

3-Month Retention Rate: 97.39%

In [55]:
#6-month checkpoint

subscribers['6_month_date'] = (
    subscribers['signup_date'] + pd.DateOffset(months=6))

print(subscribers[
        ['signup_date', '6_month_date', 'churn_date']].head())

  signup_date 6_month_date churn_date
0  2023-01-09   2023-07-09        NaT
1  2020-02-05   2020-08-05 2022-12-08
2  2022-04-15   2022-10-15        NaT
3  2024-10-10   2025-04-10        NaT
4  2020-04-12   2020-10-12 2021-12-15

In [56]:
#6-month retained flag

eligible_6_months = subscribers['6_month_date'] <= data_end_date

subscribers['retained_6_months'] = (eligible_6_months & (subscribers['churn_date'].isna() |
        (subscribers['churn_date'] > subscribers['6_month_date'])))

print("Eligible for 6-month retention:", eligible_6_months.sum())
print("Retained at 6 months:", subscribers['retained_6_months'].sum())

Eligible for 6-month retention: 13941
Retained at 6 months: 13244

In [57]:
#6-month retention rate

retention_6_months = (subscribers['retained_6_months'].sum() /
    eligible_6_months.sum()) * 100

print(f"6-Month Retention Rate: {retention_6_months:.2f}%")

6-Month Retention Rate: 95.00%

In [58]:
#12-month checkpoint

subscribers['12_month_date'] = (subscribers['signup_date'] + pd.DateOffset(months=12))

print(subscribers[['signup_date', '12_month_date', 'churn_date']].head())

  signup_date 12_month_date churn_date
0  2023-01-09    2024-01-09        NaT
1  2020-02-05    2021-02-05 2022-12-08
2  2022-04-15    2023-04-15        NaT
3  2024-10-10    2025-10-10        NaT
4  2020-04-12    2021-04-12 2021-12-15

In [60]:
#12-month retained flag


eligible_12_months = subscribers['12_month_date'] <= data_end_date

subscribers['retained_12_months'] = (eligible_12_months &
    (subscribers['churn_date'].isna() |
        (subscribers['churn_date'] > subscribers['12_month_date'])))

print("Eligible for 12-month retention:", eligible_12_months.sum())
print("Retained at 12 months:", subscribers['retained_12_months'].sum())

Eligible for 12-month retention: 12641
Retained at 12 months: 11623

In [61]:
#12-month retention rate

retention_12_months = (subscribers['retained_12_months'].sum() /
    eligible_12_months.sum()) * 100

print(f"12-Month Retention Rate: {retention_12_months:.2f}%")

12-Month Retention Rate: 91.95%

In [63]:
#Optional Cohort Retention table

cohort_retention_results = pd.DataFrame({
    'Retention Milestone': [
        '3-Month Retention',
        '6-Month Retention',
        '12-Month Retention'],
    'Eligible Subscribers': [
        eligible_3_months.sum(),
        eligible_6_months.sum(),
        eligible_12_months.sum()],
    'Retained Subscribers': [
        subscribers['retained_3_months'].sum(),
        subscribers['retained_6_months'].sum(),
        subscribers['retained_12_months'].sum()],
    'Retention Rate': [
        retention_3_months,
        retention_6_months,
        retention_12_months]})

cohort_retention_results['Retention Rate'] = (
    cohort_retention_results['Retention Rate'].map(
        lambda x: f"{x:.2f}%"))

cohort_retention_results.style.hide(axis="index")